name: Build and Deploy

on:
  push:
    branches:
      - deply

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: ssh-scp-ssh-pipelines
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSHPK }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          target: /home.ec2-user/AlphaCode/
          SCRIPT_BEFORE: |
            cd /home/ec2-user/nodejs
            sh ./kill.sh




  #     - name: Setup Node
  #       uses: actions/setup-node@v3.7.0
  #       with:
  #         node-version: 18

  #     - run: npm install -g yarn

  #     - name: build
  #       run: |
  #         yarn 
  #         yarn tsc
  #         yarn copy

  #     - name: checkFiles
  #       run: ls ./dist


  #     - name: Upload production-ready build files
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: production-files
  #         path: ./dist

  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: production-files
  #         path: ./dist   

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist
  #         publish_branch: dev
