name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: tsc
        uses: icrawl/action-tsc@v1
      
      - name: test
        run: ls -la

      - name: test2
        uses: actions/checkout@v3.5.3
        with:    
          ref: 'dev'
          
      - name: testend
        run: echo done
     

      # - name: Checkout dev branch
      #   run: git checkout -b dev

      # - name: add
      #   run: git add dist

      # - name: commit
      #   run: git commit -m 'test123'

      # - name: push
      #   run: git push origin dev
